name: deeptcn_env
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _mutex_mxnet=0.0.50=openblas
  - _openmp_mutex=5.1=1_gnu
  - alembic=1.14.0=pyhd8ed1ab_0
  - alsa-lib=1.2.8=h166bdaf_0
  - aom=3.5.0=h27087fc_0
  - arrow=1.3.0=pyhd8ed1ab_0
  - asttokens=3.0.0=pyhd8ed1ab_0
  - attr=2.5.2=h39aace5_0
  - aws-c-auth=0.7.3=h28f7589_1
  - aws-c-cal=0.6.1=hc309b26_1
  - aws-c-common=0.9.0=hd590300_0
  - aws-c-compression=0.2.17=h4d4d85c_2
  - aws-c-event-stream=0.3.1=h2e3709c_4
  - aws-c-http=0.7.11=h00aa349_4
  - aws-c-io=0.13.32=he9a53bd_1
  - aws-c-mqtt=0.9.3=hb447be9_1
  - aws-c-s3=0.3.14=hf3aad02_1
  - aws-c-sdkutils=0.1.12=h4d4d85c_1
  - aws-checksums=0.1.17=h4d4d85c_1
  - aws-crt-cpp=0.21.0=hb942446_5
  - aws-sdk-cpp=1.10.57=h85b1a90_19
  - backcall=0.2.0=pyh9f0ad1d_0
  - blas=2.138=openblas
  - blas-devel=3.9.0=38_h1ea3ea9_openblas
  - blinker=1.8.2=pyhd8ed1ab_0
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - brotli-python=1.0.9=py38hfa26641_7
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.11.4=h06a4308_0
  - cairo=1.16.0=ha61ee94_1012
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.15.0=py38h3931269_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - codecarbon=2.2.2=pyh1a96a4e_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - colorlog=6.9.0=pyh707e725_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.0.2=py38h43d8883_2
  - cuda-version=11.2=hb11dac2_3
  - cudatoolkit=11.2.2=hc23eb0c_13
  - cudnn=8.9.7.29=hbc23b4c_3
  - cycler=0.12.1=pyhd8ed1ab_0
  - cyrus-sasl=2.1.28=h1110e0f_3
  - dash=2.18.2=pyhd8ed1ab_0
  - dash-bootstrap-components=1.6.0=pyhd8ed1ab_0
  - dash-core-components=2.0.0=pyhd8ed1ab_1
  - dash-html-components=2.0.0=pyhd8ed1ab_1
  - dash-table=5.0.0=pyhd8ed1ab_1
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.6.7=py38h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - eigen=3.4.0=h4bd325d_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - expat=2.7.3=h3385a95_0
  - ffmpeg=5.1.2=lgpl_hd27bd3a_6
  - fftw=3.3.10=nompi_hf1063bd_110
  - fire=0.7.0=pyhd8ed1ab_0
  - flask=3.0.3=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.1=h4c34cd2_2
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.33.3=py38h0a891b7_0
  - freeglut=3.2.2=h9c3ff4c_1
  - freetype=2.13.3=h4a9f257_0
  - fuzzywuzzy=0.18.0=pyhd8ed1ab_0
  - gettext=0.25.1=h5888daf_0
  - gettext-tools=0.25.1=h5888daf_0
  - gflags=2.2.2=h5888daf_1005
  - glib=2.84.4=h5bdd934_0
  - glib-tools=2.84.4=h8875d55_0
  - glog=0.6.0=h6f12383_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.7.9=hb077bed_0
  - graphite2=1.3.14=h295c915_1
  - greenlet=3.0.3=py38h17151c0_0
  - gst-plugins-base=1.21.3=h4243ec0_1
  - gstreamer=1.21.3=h25f0c4b_1
  - gstreamer-orc=0.4.41=h17648ed_0
  - h2=4.1.0=pyhd8ed1ab_0
  - harfbuzz=6.0.0=h8e241bc_0
  - hdf5=1.12.2=nompi_h4df4325_101
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=70.1=h27087fc_0
  - idna=3.10=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.12.2=pyh41d4057_0
  - ipywidgets=8.1.5=pyhd8ed1ab_0
  - itsdangerous=2.2.0=pyhd8ed1ab_0
  - jack=1.9.22=h11f4161_0
  - jasper=2.0.33=h0ff4b12_1
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_1
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=5.8.1=pyh31011fe_0
  - jupyterlab_widgets=3.0.13=pyhd8ed1ab_0
  - kiwisolver=1.4.2=py38h43d8883_1
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7f98852_1001
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20230125.3=cxx17_h59595ed_0
  - libaec=1.1.4=h3f801dc_0
  - libarrow=12.0.1=hb87d912_8_cpu
  - libasprintf=0.25.1=h8e693c7_0
  - libasprintf-devel=0.25.1=h8e693c7_0
  - libblas=3.9.0=38_h4a7cf45_openblas
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcap=2.67=he9d0100_0
  - libcblas=3.9.0=38_h0358290_openblas
  - libclang=15.0.7=default_h127d8a8_5
  - libclang13=15.0.7=default_h5d6823c_5
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcups=2.3.3=h36d4200_3
  - libcurl=8.16.0=heebcbe5_0
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h28343ad_4
  - libffi=3.4.4=h6a678d5_1
  - libflac=1.4.3=h59595ed_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgcrypt=1.11.1=ha770c72_0
  - libgcrypt-devel=1.11.1=hb9d3cd8_0
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgcrypt-tools=1.11.1=hb9d3cd8_0
  - libgettextpo=0.25.1=h5888daf_0
  - libgettextpo-devel=0.25.1=h5888daf_0
  - libgfortran-ng=13.2.0=h69a702a_0
  - libgfortran5=13.2.0=ha4646dd_0
  - libglib=2.84.4=h77a78f3_0
  - libglu=9.0.3=h5888daf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h767d61c_7
  - libgoogle-cloud=2.12.0=hac9eb74_1
  - libgpg-error=1.55=h3f2d84a_0
  - libgrpc=1.54.3=hb20ce57_0
  - libiconv=1.17=h166bdaf_0
  - libidn2=2.3.2=h7f98852_0
  - libkrb5=1.21.3=h520c7b4_4
  - liblapack=3.9.0=38_h47877c9_openblas
  - liblapacke=3.9.0=38_h6ae95b6_openblas
  - libllvm14=14.0.6=hecde1de_4
  - libllvm15=15.0.7=hadd5161_1
  - libltdl=2.4.3a=h5888daf_0
  - libmxnet=1.9.1=openblas_h8848447_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libnuma=2.0.18=hb9d3cd8_3
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.30=h46f56fc_0
  - libopencv=4.6.0=py38h340f60e_9
  - libopengl=1.7.0=ha4b6fd6_2
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h2ed474d_0
  - libpq=15.3=hbcd7760_1
  - libprotobuf=3.21.12=hfc55251_2
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.20=heac8642_0
  - libsqlite=3.51.0=h0c1763c_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libsystemd0=253=h8c4010b_1
  - libtasn1=4.20.0=hb03c661_1
  - libthrift=0.18.1=h5e4af38_0
  - libtiff=4.5.1=hffd6297_1
  - libtool=2.5.4=h5888daf_0
  - libudev1=253=h0b41bf4_1
  - libunistring=0.9.10=h7f98852_0
  - libutf8proc=2.8.0=hf23e847_1
  - libuuid=1.41.5=h5eee18b_0
  - libva=2.18.0=h0b41bf4_0
  - libvorbis=1.3.7=h54a6638_2
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.10.3=hca2bb57_4
  - libzlib=1.3.1=hb25bd0a_0
  - lmdb=0.9.29=h166bdaf_1
  - lz4-c=1.9.4=h6a678d5_1
  - mako=1.3.5=pyhd8ed1ab_0
  - markupsafe=2.1.1=py38h0a891b7_1
  - matplotlib=3.7.2=py38h578d9bd_0
  - matplotlib-base=3.7.2=py38h1128e8f_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mpg123=1.32.9=hc50e24c_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql=8.0.32=h27aab58_0
  - mysql-client=8.0.32=hb89bdb7_0
  - mysql-common=8.0.32=ha901b37_0
  - mysql-devel=8.0.32=ha901b37_0
  - mysql-libs=8.0.32=hd7da12d_0
  - mysql-server=8.0.32=h02d985f_0
  - nccl=2.27.3.1=h03a54cd_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - nettle=3.9.1=h7ab15ed_0
  - nomkl=3.0=0
  - nspr=4.38=h29cc59b_0
  - nss=3.117=h445c969_0
  - numpy=1.22.3=py38h99721a1_2
  - openblas=0.3.30=h5426c36_0
  - openblas-devel=0.3.30=h557178c_0
  - opencv=4.6.0=py38h578d9bd_9
  - openh264=2.3.1=hcb278e6_2
  - openjpeg=2.5.2=he7f1fd0_0
  - openldap=2.6.5=h389dcaa_0
  - openssl=3.1.8=h7b32b05_0
  - optuna=4.5.0=pyhd8ed1ab_0
  - orc=1.9.0=h2f23424_1
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=25.0=pyh29332c3_1
  - pandas=1.4.2=py38h47df419_1
  - parso=0.8.4=pyhd8ed1ab_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pcre2=10.46=hf426167_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.4.0=py38h5eee18b_0
  - pip=24.2=py38h06a4308_0
  - pixman=0.46.4=h7934f7d_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - plotly=5.24.1=pyhd8ed1ab_0
  - pooch=1.8.2=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - prompt_toolkit=3.0.48=hd8ed1ab_1
  - psutil=5.9.1=py38h0a891b7_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pulseaudio=16.1=hcb278e6_3
  - pulseaudio-client=16.1=h5195f5e_3
  - pulseaudio-daemon=16.1=ha8d29e2_3
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - py-cpuinfo=9.0.0=pyhd8ed1ab_0
  - py-opencv=4.6.0=py38h6f1a3b6_9
  - pyarrow=12.0.1=py38h39356d1_8_cpu
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pynvml=11.5.3=pyhd8ed1ab_1
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.4=py38hfa26641_0
  - pyqt5-sip=12.9.0=py38hfa26641_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.20=he870216_0
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-levenshtein=0.12.2=py38h0a891b7_2
  - python_abi=3.8=2_cp38
  - pytz=2024.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py38h2019614_0
  - pyzmq=25.1.2=py38h6a678d5_0
  - qt-main=5.15.6=h602db52_6
  - rdma-core=28.9=h59595ed_1
  - re2=2023.03.02=h8c504da_0
  - readline=8.3=hc2a1206_0
  - requests=2.32.3=pyhd8ed1ab_0
  - retrying=1.3.3=pyhd8ed1ab_3
  - s2n=1.3.49=h06160fa_0
  - scikit-learn=1.1.1=py38hf80bbf7_0
  - scipy=1.10.1=py38h32ae08f_1
  - seaborn=0.13.2=hd8ed1ab_2
  - seaborn-base=0.13.2=pyhd8ed1ab_2
  - setuptools=75.1.0=py38h06a4308_0
  - sip=6.5.1=py38h709712a_2
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=hdb0a2a9_1
  - sqlalchemy=2.0.32=py38h2019614_0
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.13.2=py38h6c62de6_0
  - svt-av1=1.4.1=hcb278e6_0
  - tenacity=9.0.0=pyhd8ed1ab_0
  - termcolor=2.4.0=pyhd8ed1ab_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.14=h39e8969_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tornado=6.1=py38h0a891b7_3
  - tqdm=4.67.1=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - types-python-dateutil=2.9.0.20241003=pyhff2d567_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - ucx=1.14.1=h64cca9d_5
  - unicodedata2=14.0.0=py38h0a891b7_1
  - urllib3=2.2.3=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - werkzeug=3.0.6=pyhd8ed1ab_0
  - wheel=0.44.0=py38h06a4308_0
  - widgetsnbextension=4.0.13=pyhd8ed1ab_0
  - x264=1!157.20191217=h7b6447c_0
  - xcb-util=0.4.0=h516909a_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h516909a_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h516909a_0
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-inputproto=2.3.2=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xorgproto=2024.1=hb9d3cd8_1
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h280c20c_3
  - zeromq=4.3.5=hb0a5e54_1
  - zipp=3.21.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - zstandard=0.19.0=py38h5eee18b_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - graphviz==0.8.4
      - master-thesis==1.0.0
      - mxboard==0.1.0
      - mxnet-cu112==1.9.1
      - protobuf==3.20.3
prefix: /home/voron/miniconda3/envs/deeptcn_env
