name: main_env
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - adagio=0.2.6=pyhd8ed1ab_1
  - alsa-lib=1.2.14=hb9d3cd8_0
  - antlr-python-runtime=4.11.1=pyhd8ed1ab_0
  - antlr4-python3-runtime=4.11.1=pyh1a96a4e_0
  - appdirs=1.4.4=pyhd8ed1ab_1
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - aws-c-auth=0.9.1=h194c533_5
  - aws-c-cal=0.9.8=h346e085_0
  - aws-c-common=0.12.5=hb03c661_1
  - aws-c-compression=0.3.1=h7e655bb_7
  - aws-c-event-stream=0.5.6=h1deb5b9_4
  - aws-c-http=0.10.7=had4b759_1
  - aws-c-io=0.23.2=hbff472d_2
  - aws-c-mqtt=0.13.3=h8ba2272_8
  - aws-c-s3=0.8.6=h493c25d_7
  - aws-c-sdkutils=0.2.4=h7e655bb_2
  - aws-checksums=0.2.7=h7e655bb_3
  - aws-crt-cpp=0.35.0=h719b17a_2
  - aws-sdk-cpp=1.11.606=h522d481_6
  - azure-core-cpp=1.16.1=h3a458e0_0
  - azure-identity-cpp=1.13.2=h3a5f585_1
  - azure-storage-blobs-cpp=12.15.0=h2a74896_1
  - azure-storage-common-cpp=12.11.0=h3d7a050_1
  - azure-storage-files-datalake-cpp=12.13.0=hf38f1be_1
  - blinker=1.9.0=pyhff2d567_0
  - brotli=1.2.0=h41a2e66_0
  - brotli-bin=1.2.0=hf2c8021_0
  - brotli-python=1.2.0=py313h09d1b84_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.11.4=h06a4308_0
  - cairo=1.18.4=h3394656_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=1.17.1=py313hfab6e84_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.0=pyh707e725_0
  - cloudpickle=3.1.2=pyhd8ed1ab_0
  - codecarbon=2.2.2=pyh1a96a4e_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py313h7037e92_3
  - coreforecast=0.0.16=py313h7037e92_1
  - cpython=3.13.9=py313hd8ed1ab_101
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dash=3.2.0=pyhd8ed1ab_0
  - dash-bootstrap-components=2.0.4=pyhcf101f3_0
  - dash-core-components=2.0.0=pyhd8ed1ab_1
  - dash-html-components=2.0.0=pyhd8ed1ab_2
  - dash-table=5.0.0=pyhd8ed1ab_1
  - dbus=1.16.2=h3c4dab8_0
  - debugpy=1.8.17=py313h5d5ffb9_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - double-conversion=3.3.1=h5888daf_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=hecca717_0
  - fire=0.7.1=pyhd8ed1ab_0
  - flask=3.1.2=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.60.1=py313h3dea7bd_0
  - freetype=2.14.1=ha770c72_0
  - fs=2.4.16=pyhd8ed1ab_0
  - fsspec=2025.10.0=pyhd8ed1ab_0
  - fugue=0.9.2=pyhd8ed1ab_0
  - fuzzywuzzy=0.18.0=pyhd8ed1ab_1
  - gflags=2.2.2=h5888daf_1005
  - glog=0.7.1=hbabe93e_0
  - graphite2=1.3.14=hecca717_2
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.2.0=h15599e2_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyha191276_0
  - ipython=9.7.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - kagglehub=0.3.8=pyhd8ed1ab_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py313hc8edb43_2
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h0aef613_1
  - levenshtein=0.27.3=py313h7033f15_0
  - libabseil=20250512.1=cxx17_hba17884_0
  - libarrow=22.0.0=h99e40f8_3_cpu
  - libarrow-acero=22.0.0=h635bf11_3_cpu
  - libarrow-compute=22.0.0=h8c2c5c3_3_cpu
  - libarrow-dataset=22.0.0=h635bf11_3_cpu
  - libarrow-substrait=22.0.0=h3f74fd7_3_cpu
  - libblas=3.9.0=38_h4a7cf45_openblas
  - libbrotlicommon=1.2.0=h09219d5_0
  - libbrotlidec=1.2.0=hd53d788_0
  - libbrotlienc=1.2.0=h02bd7ab_0
  - libcblas=3.9.0=38_h0358290_openblas
  - libclang-cpp18.1=18.1.8=default_h99862b1_15
  - libclang-cpp21.1=21.1.5=default_h99862b1_1
  - libclang13=21.1.5=default_h746c552_1
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.17.0=h4e3cde8_0
  - libdeflate=1.22=hb9d3cd8_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.1=h32235b2_2
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h4751f2c_7
  - libgoogle-cloud=2.39.0=hdb79228_0
  - libgoogle-cloud-storage=2.39.0=hdbdcf42_0
  - libgrpc=1.73.1=h3288cfb_1
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.9.0=38_h47877c9_openblas
  - libllvm18=18.1.8=default_h99862b1_10
  - libllvm21=21.1.5=hf7376ad_0
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=h5eee18b_0
  - libnghttp2=1.67.0=had1ee68_0
  - libntlm=1.8=hb9d3cd8_0
  - libopenblas=0.3.30=pthreads_h94d23a6_3
  - libopengl=1.7.0=ha4b6fd6_2
  - libopentelemetry-cpp=1.21.0=hb9b0907_1
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_1
  - libparquet=22.0.0=h7376487_3_cpu
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h421ea60_1
  - libpq=17.6=h3675c94_2
  - libprotobuf=6.31.1=h49aed37_2
  - libre2-11=2025.11.05=h7b12aa8_0
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.51.0=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libthrift=0.22.0=h454ac66_1
  - libtiff=4.7.0=he137b08_1
  - libutf8proc=2.11.0=hb04c3b8_0
  - libuuid=2.41.2=he9a06e4_0
  - libvulkan-loader=1.4.328.1=h5279c79_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.13.0=hca5e8e5_0
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libxslt=1.1.43=h711ed8c_1
  - libzlib=1.3.1=hb25bd0a_0
  - llvmlite=0.45.1=py313hdd307be_0
  - lz4-c=1.10.0=h5888daf_1
  - markupsafe=3.0.3=py313h3dea7bd_0
  - matplotlib=3.10.7=py313h78bf25f_0
  - matplotlib-base=3.10.7=py313h683a580_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - mysql-common=8.3.0=h70512c7_5
  - mysql-libs=8.3.0=ha479ceb_5
  - narwhals=2.11.0=pyhcf101f3_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nlohmann_json=3.12.0=h54a6638_1
  - numba=0.62.1=py313hd8e3f9f_0
  - numpy=2.3.4=py313hf6604e3_0
  - nvidia-ml-py=13.580.82=pyhd8ed1ab_0
  - openjpeg=2.5.3=h55fea9a_1
  - openldap=2.6.10=he970967_0
  - openssl=3.6.0=h26f9b46_0
  - orc=2.2.1=hd747db4_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py313h08cd8bf_1
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.46=h1321c63_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pillow=11.3.0=py313ha492abd_3
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h54a6638_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - plotly=6.4.0=pyhd8ed1ab_0
  - prometheus-cpp=1.3.0=ha5d0236_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py313h54dd161_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-cpuinfo=9.0.0=pyhd8ed1ab_1
  - pyarrow=22.0.0=py313h78bf25f_0
  - pyarrow-core=22.0.0=py313he109ebe_0_cpu
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pynvml=13.0.1=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyside6=6.9.2=py313h85046ba_2
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.13.9=hc97d973_101_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.13.9=h4df99d1_101
  - python-levenshtein=0.27.3=pyh332efcf_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.13=1_cp313
  - pytz=2025.2=pyhd8ed1ab_0
  - pyzmq=27.1.0=py312hfb55c3c_0
  - qhull=2020.2=h434a139_5
  - qt6-main=6.9.2=h994258b_2
  - rapidfuzz=3.14.3=py313h7033f15_1
  - re2=2025.11.05=h5301d42_0
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=pyhd8ed1ab_0
  - retrying=1.4.2=pyhe01879c_0
  - s2n=1.6.0=h8399546_1
  - scikit-learn=1.7.2=py313h06d4379_0
  - scipy=1.16.3=py313h11c21cd_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.9.0=py313h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_0
  - sqlite=3.51.0=h2a70700_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsforecast=1.7.6=pyhd8ed1ab_0
  - statsmodels=0.14.5=py313h29aa505_1
  - termcolor=3.2.0=pyhd8ed1ab_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.2=py313h07c4f96_2
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - triad=1.0.0=pyhd8ed1ab_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - utilsforecast=0.2.14=pyhd8ed1ab_0
  - wayland=1.24.0=hdac8c69_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=py313h06a4308_0
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - zstandard=0.25.0=py313h54dd161_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - cupy-cuda13x==13.6.0
      - fastrlock==0.8.3
      - h5netcdf==1.7.3
      - h5py==3.15.1
      - master-thesis==1.0.0
      - xarray==2025.11.0
      - xarray-einstats==0.9.1
prefix: /home/voron/miniconda3/envs/main_env
